spring:
  application:
    name: UserManagmentService
  datasource:
    url: jdbc:mysql://localhost:3306/project
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    user:
      name: root
      password: root

server:
  port: 8081

logging:
  level:
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG



eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true


management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always

info:
  app:
    name: user-service
    version: 1.0.0


jwt:
  secret: ${JWT_SECRET}
  expiration:  ${JWT_EXPIRATION:3600000}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION:604800000}