spring:
  application:
    name: gatewayserver
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: false
              lowerCaseServiceId: true
          routes:
            - id: order-service
              uri: lb://ORDERSERVICE
              predicates:
                - Path=/api/orders/**        # your custom path
              filters:
                - RewritePath=/api/orders/(?<remaining>.*), /${remaining}

            - id: payment-service
              uri: lb://PAYMENTSERVICE
              predicates:
                - Path=/api/payments/**
              filters:
                - RewritePath=/api/payments/(?<remaining>.*), /${remaining}

            - id: user-service
              uri: lb://USERMANAGMENTSERVICE
              predicates:
                - Path=/api/users/**
              filters:
                - RewritePath=/api/users/(?<remaining>.*), /${remaining}


server:
  port: 8072

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true        # ← explicitly enable gateway endpoint

info:
  app:
    name: gatewayserver
    version: 1.0.0